yml

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -28,9 +28,20 @@ jobs:
 
     - name: Start FastAPI Application
       run: |
-        uvicorn main:app --host 0.0.0.0 --port 8000
-      # 注意这里端口使用的是8000而不是80，因为80端口通常被其他服务占用或需要root权限
-      # 结束工作流的策略通常是通过设置timeout-minutes或者让job在启动服务后立即退出
+        nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
+        echo "Server started, waiting for it to be ready..."
+        sleep 10 # 等待一段时间确保服务器已准备好接收请求
       env:
         PORT: 8000
-      timeout-minutes: 1 # 设置超时时间以结束工作流，可根据实际需要调整
+  
+    - name: Test FastAPI Application
+      run: |
+        # 发送GET请求并检查响应状态
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000)
+        if [ "$RESPONSE" -eq 200 ]; then
+          echo "Application is running successfully."
+          exit 0
+        else
+          echo "Failed to start the application or receive a successful response."
+          exit 1
+        fi
